# Generated by Django 5.2.7 on 2026-02-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='executor',
        ),
    ]
